### PR TITLE
#3606 Bond length between the base and the sugar is not standart if the selected group is forming an n-agon with 12 or more than 12 points

### LINKED ISSUE #3606: Bond length between the base and the sugar is not standart if the selected group is forming an n-agon with 12 or more than 12 points
**Steps to Reproduce**
1. Open Macromolecules - Flex mode (clean canvas)
2. Load from HELM: `RNA1{r(A).r(A).r(A).r(A).r(A).r(A).r(A).r(A).r(A).r(A).r(A).r(A)}$RNA1,RNA1,1:R1-23:R2$$$V2.0`
3. Open the context menu and click `Arrange as a ring` option

**Actual behavior**
The bond length between the base and the sugar is shorter than the standard length.

Image

**Expected behavior**
The bond length between the base and the sugar matches the standard length.

As per [requirement](https://github.com/epam/Indigo/issues/3196):
> 6.3. If the selected group is forming an n-agon with 12 or more than 12 points, the bases should be located inside of the circular structure, keeping the full standard bond length between the base and the sugar.

**Found in Environment:**

- Ketcher Version 3.15.0-rc.1 Build at 2026-04-02; 15:41:30
- Indigo Version 1.43.0-rc.1.0-gd74653443-wasm32-wasm-clang-19.0.0
- Chrome Version 146.0.7680.180 (Official Build) (64-bit)
- Win11

Found while testing: #3308

### PR DESCRIPTION
**Pull request by even1024**
## Generic request
- [ ] PR name follows the pattern `#1234 – issue name`
- [ ] branch name does not contain '#'
- [ ] base branch (master or release/xx) is correct
- [ ] PR is linked with the issue
- [ ] task status changed to "Code review"
- [ ] code follows product standards
- [ ] regression tests updated

### CODE REVIEW

File: core/indigo-core/layout/src/molecule_layout_graph_assign.cpp [hunk 1]
```diff
@@ -1641,13 +1641,22 @@ void MoleculeLayoutGraph::_assignFinalCoordinates(float bond_length, const Array
...
+        // Requirement #3196 §6.3: for n-agon >= 12 bases must keep the full
+        // standard bond length; only smaller rings use the shortened 0.75 value.
+        std::vector<int> large_inner_cycle_vertices;
         for (auto vx_idx : vertices())
         {
             auto& lvx = _layout_vertices[vx_idx];
             if (lvx.is_inner_cycle)
-                inner_cycle_vertices.push_back(vx_idx);
+            {
+                if (lvx.inner_cycle_size >= 12)
```
Comment (AlexanderSavelyev) [inline core/indigo-core/layout/src/molecule_layout_graph_assign.cpp]: add constant for 12

File: core/indigo-core/layout/src/molecule_layout_graph_assign.cpp [hunk 2]
```diff
@@ -2103,7 +2112,10 @@ void MoleculeLayoutGraph::_markInnerVertices(const MoleculeLayoutGraph& componen
                 for (int k = vx_nei.neiBegin(); k < vx_nei.neiEnd(); k = vx_nei.neiNext(k), ++nei_count)
                     ;
                 if (nei_count == 1 && component.vertexCount() > 5)
```
Comment (AlexanderSavelyev) [inline core/indigo-core/layout/src/molecule_layout_graph_assign.cpp]: add constant for 5

**Review by AlexanderSavelyev — CHANGES_REQUESTED** [review]

**Review by AlexanderSavelyev — APPROVED** [review]
