### PR TITLE
#3249 Unable to load Mol v3000 file with R-group fragment inside - system throws exception

### LINKED ISSUE #3249: Unble to load Mol v3000 file with R-group fagment inside - system throws exception
**Steps to Reproduce**
1. Go to Molecules mode (empty canvas)
2. Load from KET: [Memory problem.zip](https://github.com/user-attachments/files/21618784/Memory.problem.zip)
Image
<details><summary>Memory.problem.ket</summary>
<p>

```
{
    "root": {
        "nodes": [
            {
                "$ref": "rg1"
            },
            {
                "$ref": "mol0"
            },
            {
                "$ref": "mol1"
            },
            {
                "$ref": "mol2"
            },
            {
                "type": "arrow",
                "data": {
                    "mode": "open-angle",
                    "pos": [
                        {
                            "x": 1.7694768904112612,
                            "y": 0.11120053721286327,
                            "z": 0
                        },
                        {
                            "x": 6.707211130922865,
                            "y": 0.11120053721286327,
                            "z": 0
                        }
                    ]
                }
            },
            {
                "type": "plus",
                "location": [
                    14.951295072229447,
                    -0.34334491733259115,
                    0
                ],
                "prop": {}
            },
            {
                "type": "plus",
                "location": [
                    10.27597039690477,
                    -0.01866959265726631,
                    0
                ],
                "prop": {}
            }
        ],
        "connections": [],
        "templates": []
    },
    "rg1": {
        "rlogic": {
            "number": 1
        },
        "type": "rgroup",
        "atoms": [
            {
                "label": "*",
                "location": [
                    12.090764965889763,
                    0.4744170442850775,
                    0
                ]
            },
            {
                "label": "*",
                "location": [
                    13.820718883720632,
                    0.47490213476326365,
                    0
                ]
            },
            {
                "label": "C",
                "location": [
                    12.957379105169077,
                    0.9744240546753109,
                    0
                ]
            },
            {
                "label": "C",
                "location": [
                    13.820718883720632,
                    -0.5258395217344838,
                    0
                ]
            },
            {
                "label": "C",
                "location": [
                    12.090764965889763,
                    -0.5303266086577045,
                    0
                ]
            },
            {
                "label": "*",
                "location": [
                    12.95956201232091,
                    -1.025240169026986,
                    0
                ]
            }
        ],
        "bonds": [
            {
                "type": 2,
                "atoms": [
                    2,
                    0
                ]
            },
            {
                "type": 1,
                "atoms": [
                    0,
                    4
                ]
            },
            {
                "type": 2,
                "atoms": [
                    4,
                    5
                ]
            },
            {
                "type": 1,
                "atoms": [
                    5,
                    3
                ]
            },
            {
                "type": 2,
                "atoms": [
                    3,
                    1
                ]
            },
            {
                "type": 1,
                "atoms": [
                    1,
                    2
                ]
            }
        ],
        "stereoFlagPosition": {
            "x": 13.820718883720632,
            "y": -1.9744240546753102,
            "z": 0
        }
    },
    "mol0": {
        "type": "molecule",
        "atoms": [
            {
                "label": "*",
                "location": [
                    -1.4086045480207483,
                    0.3382341040965463,
                    0
                ]
            },
            {
                "label": "*",
                "location": [
                    0.32134936981012263,
                    0.33871919457473065,
                    0
                ]
            },
            {
                "label": "C",
                "location": [
                    -0.5419904087414364,
                    0.8382411144867792,
                    0
                ]
            },
            {
                "label": "C",
                "location": [
                    0.32134936981012263,
                    -0.6620224619230153,
                    0
                ]
            },
            {
                "label": "C",
                "location": [
                    -1.4086045480207483,
                    -0.666509548846236,
                    0
                ]
            },
            {
                "label": "*",
                "location": [
                    -0.5398075015895989,
                    -1.1614231092155163,
                    0
                ]
            }
        ],
        "bonds": [
            {
                "type": 2,
                "atoms": [
                    2,
                    0
                ]
            },
            {
                "type": 1,
                "atoms": [
                    0,
                    4
                ]
            },
            {
                "type": 2,
                "atoms": [
                    4,
                    5
                ]
            },
            {
                "type": 1,
                "atoms": [
                    5,
                    3
                ]
            },
            {
                "type": 2,
                "atoms": [
                    3,
                    1
                ]
            },
            {
                "type": 1,
                "atoms": [
                    1,
                    2
                ]
            }
        ],
        "stereoFlagPosition": {
            "x": 0.32134936981012263,
            "y": -1.8382411144867792,
            "z": 0
        }
    },
    "mol1": {
        "type": "molecule",
        "atoms": [
            {
                "label": "*",
                "location": [
                    16.339910747154605,
                    0.3494421683655239,
                    0
                ],
                "attachmentPoints": 3
            },
            {
                "label": "*",
                "location": [
                    18.069864664985474,
                    0.34992725884370823,
                    0
                ],
                "attachmentPoints": 1
            },
            {
                "label": "C",
                "location": [
                    17.206524886433918,
                    0.8494491787557565,
                    0
                ]
            },
            {
                "label": "C",
                "location": [
                    18.069864664985474,
                    -0.6508143976540386,
                    0
                ]
            },
            {
                "label": "C",
                "location": [
                    16.339910747154605,
                    -0.6553014845772585,
                    0
                ]
            },
            {
                "label": "*",
                "location": [
                    17.20870779358576,
                    -1.1502150449465405,
                    0
                ],
                "attachmentPoints": 2
            }
        ],
        "bonds": [
            {
                "type": 2,
                "atoms": [
                    2,
                    0
                ]
            },
            {
                "type": 1,
                "atoms": [
                    0,
                    4
                ]
            },
            {
                "type": 2,
                "atoms": [
                    4,
                    5
                ]
            },
            {
                "type": 1,
                "atoms": [
                    5,
                    3
                ]
            },
            {
                "type": 2,
                "atoms": [
                    3,
                    1
                ]
            },
            {
                "type": 1,
                "atoms": [
                    1,
                    2
                ]
            }
        ],
        "stereoFlagPosition": {
            "x": 18.069864664985474,
            "y": -1.8494491787557572,
            "z": 0
        }
    },
    "mol2": {
        "type": "molecule",
        "atoms": [
            {
                "type": "rg-label",
                "location": [
                    7.841619184624923,
                    0.4327587523118924,
                    0
                ],
                "$refs": [
                    "rg-1"
                ]
            },
            {
                "type": "rg-label",
                "location": [
                    9.571573102455794,
                    0.43324384279007677,
                    0
                ],
                "$refs": [
                    "rg-3"
                ]
            },
            {
                "type": "rg-label",
                "location": [
                    8.708233323904237,
                    0.9327657627021253,
                    0
                ],
                "$refs": [
                    "rg-2"
                ]
            },
            {
                "type": "rg-label",
                "location": [
                    9.571573102455794,
                    -0.5674978137076689,
                    0
                ],
                "$refs": [
                    "rg-4"
                ]
            },
            {
                "type": "rg-label",
                "location": [
                    7.841619184624923,
                    -0.6136431926040742,
                    0
                ],
                "$refs": [
                    "rg-6"
                ]
            },
            {
                "type": "rg-label",
                "location": [
                    8.710416231056074,
                    -1.066898461000171,
                    0
                ],
                "$refs": [
                    "rg-5"
                ]
            }
        ],
        "bonds": [
            {
                "type": 2,
                "atoms": [
                    2,
                    0
                ]
            },
            {
                "type": 1,
                "atoms": [
                    0,
                    4
                ]
            },
            {
                "type": 2,
                "atoms": [
                    4,
                    5
                ]
            },
            {
                "type": 1,
                "atoms": [
                    5,
                    3
                ]
            },
            {
                "type": 2,
                "atoms": [
                    3,
                    1
                ]
            },
            {
                "type": 1,
                "atoms": [
                    1,
                    2
                ]
            }
        ]
    }
}
``` 

</p>
</details> 

3. Press Save button and save to `MDL Rxnfile V3000`
4. Load resulted rxn file back as New project

**Actual behavior**
System throws exception: `Convert error!
Given string could not be loaded as (query or plain) molecule or reaction, see the error messages: 'scanner: readIntFix(3): invalid number representation: "M  "', 'molfile loader: unexpected string in reaction: M  V30 BEGIN RGROUP 1', 'SEQUENCE loader: Invalid AxoLabs sequence: expected 5'- got $RX', 'scanner: readIntFix(3): invalid number representation: "M  "', 'scanner: readIntFix(3): invalid number representation: "M  "', 'molfile loader: unexpected string in reaction: M  V30 BEGIN RGROUP 1'`
Image

**Expected behavior**
No exception, reaction loaded
Image

**Versions**
- Ketcher Version 3.8.0-rc.1 Build at 2025-09-26; 10:03:15
- Indigo Version 1.37.0-dev.4.0-g16ce0dfeb-wasm32-wasm-clang-19.0.0
- Chrome Version 140.0.7339.208 (Official Build) (64-bit)
- Win10

Found while testing - https://github.com/epam/ketcher/issues/4109, https://github.com/epam/Indigo/issues/1426

### PR DESCRIPTION
**Pull request by even1024**
## Generic request
- [ ] PR name follows the pattern `#1234 – issue name`
- [ ] branch name does not contain '#'
- [ ] base branch (master or release/xx) is correct
- [ ] PR is linked with the issue
- [ ] task status changed to "Code review"
- [ ] code follows product standards
- [ ] regression tests updated

### CODE REVIEW

File: core/indigo-core/molecule/src/base_molecule.cpp [hunk 1]
```diff
@@ -1277,6 +1278,64 @@ int BaseMolecule::getSingleAllowedRGroup(int atom_idx)
     throw Error("getSingleAllowedRGroup(): no r-groups defined on atom #%d", atom_idx);
 }
 
+void BaseMolecule::removeUnusedRGroups()
```
Comment (AlexanderSavelyev) [inline core/indigo-core/molecule/src/base_molecule.cpp:1281]: add comment what does mean unused r-group

File: core/indigo-core/reaction/src/reaction_json_loader.cpp [hunk 2]
```diff
@@ -127,6 +127,7 @@ void ReactionJsonLoader::parseOneArrowReaction(BaseReaction& rxn)
         Filter filter(_pmol->getDecomposition().ptr(), Filter::EQ, index);
 
         mol->makeSubmolecule(*_pmol, filter, 0, 0);
```
Comment (AlexanderSavelyev) [inline core/indigo-core/reaction/src/reaction_json_loader.cpp]: add comment why do we remove unused rgroups

File: core/indigo-core/reaction/src/reaction_multistep_detector.cpp [hunk 3]
```diff
@@ -251,6 +251,7 @@ std::unique_ptr<BaseMolecule> ReactionMultistepDetector::extractComponent(int in
     else
         component = std::make_unique<Molecule>();
     component->makeSubmolecule(_bmol, filter, 0, 0);
+    component->removeUnusedRGroups();
```
Comment (AlexanderSavelyev) [inline core/indigo-core/reaction/src/reaction_multistep_detector.cpp]: add comment why do we remove unused r-groups

**Review by AlexanderSavelyev — CHANGES_REQUESTED** [review]

File: core/indigo-core/molecule/src/base_molecule.cpp (hunk 1 above)
Comment (even1024) [reply core/indigo-core/molecule/src/base_molecule.cpp:1281]: fixed

File: core/indigo-core/reaction/src/reaction_multistep_detector.cpp (hunk 3 above)
Comment (even1024) [reply core/indigo-core/reaction/src/reaction_multistep_detector.cpp]: fixed

**Review by AlexanderSavelyev — APPROVED** [review]
