### PR TITLE
#3220 System ignores implicitly provided file format on load content thru Paste From Clipboard way

### LINKED ISSUE #3220: Preview: System ignores implicitly provided file format on load content thru Paste From Clipboard way
**Steps to Reproduce**
1. Go to Macromolecules canvas - Flex mode (empty canvas)
2. Press `Open...` button -> press `Paste From Clipboard`
3. In appeared Open Structure dialog select `MDL Molfile V3000` in type selector
4. Paste `sdfsdfsd` value
Image

5. Press `Add to Canvas` button

**Actual behavior**
System loads peptide sequence ignoring selected format
Image

**Expected behavior**
System throws error message.
Image

**Versions**
- Ketcher Version 3.8.0-rc.1 Build at 2025-09-26; 10:03:15
- Indigo Version 1.37.0-dev.4.0-g16ce0dfeb-wasm32-wasm-clang-19.0.0
- Chrome Version 140.0.7339.208 (Official Build) (64-bit)
- Win10

Found while testing - https://github.com/epam/ketcher/issues/4109, https://github.com/epam/Indigo/issues/1426

### PR DESCRIPTION
**Pull request by even1024**
## Generic request
- [ ] PR name follows the pattern `#1234 – issue name`
- [ ] branch name does not contain '#'
- [ ] base branch (master or release/xx) is correct
- [ ] PR is linked with the issue
- [ ] task status changed to "Code review"
- [ ] code follows product standards
- [ ] regression tests updated

### CODE REVIEW

File: api/wasm/indigo-ketcher/indigo-ketcher.cpp [hunk 1]
```diff
@@ -296,13 +296,36 @@ namespace indigo
...
-                                      "sequence-type", "upc",    "nac"};
+        std::set<std::string> to_skip{"smiles", "smarts", "output-content-type", "outputFormat", "monomerLibrary", "sequence-type", "upc", "nac"};
         for (const auto& option : options)
         {
             if (to_skip.count(option.first) < 1)
             {
-                _checkResult(indigoSetOption(option.first.c_str(), option.second.c_str()));
+                if (option.first == "input-format")
+                {
+                    static const std::unordered_map<std::string, std::string> format_mapping = {{"chemical/x-mdl-molfile", "mol"},
```
Comment (AlexanderSavelyev) [inline api/wasm/indigo-ketcher/indigo-ketcher.cpp]: please move to the C++ code the mapping. It should be in one place

File: utils/indigo-service/backend/service/v2/indigo_api.py [hunk 2]
```diff
@@ -28,6 +28,22 @@
 
 tls = local()
 
+# MIME type to short format mapping for input-format option
+MIME_TO_FORMAT = {
```
Comment (AlexanderSavelyev) [inline utils/indigo-service/backend/service/v2/indigo_api.py]: please move to the C++ code the mapping. It should be in one place

**Review by AlexanderSavelyev — CHANGES_REQUESTED** [review]

File: api/wasm/indigo-ketcher/indigo-ketcher.cpp (hunk 1 above)
Comment (even1024) [reply api/wasm/indigo-ketcher/indigo-ketcher.cpp]: fixed

File: utils/indigo-service/backend/service/v2/indigo_api.py (hunk 2 above)
Comment (even1024) [reply utils/indigo-service/backend/service/v2/indigo_api.py]: fixed

**Review by AlexanderSavelyev — APPROVED** [review]
