### PR TITLE
#3215 Export to SMARTS works wrong for R-Groups

### LINKED ISSUE #3215: Export to SMARTS works wrong for R-Groups
**Steps to Reproduce**
1. Go to Molecules mode (empty canvas)
2. Load from Extended SMILES: `[*:3]%87%88.[*:2]%89%87.[*:1]%87%89.[*:6]%89%87.[*:5]%87%89.[*:4]%88%87 |$_R3;_R2;_R1;_R6;_R5;_R4$|`
Image

3. Save canvas to SMARTS

**Actual behavior**
Export result: `[*:4]%87%88.[*:2]%89-%87.[*:1]%87-%89.[*:32]%89-%87.[*:16]%87-%89.[*:8]-%88-%87`
Image

if loaded it contains wrong R-Groups:
Image

**Expected behavior**
Export result: `[*:3]%87%88.[*:2]%89-%87.[*:1]%87-%89.[*:6]%89-%87.[*:5]%87-%89.[*:4]-%88-%87`
If loaded:
Image

**Versions**
- Ketcher Version 3.8.0-rc.1 Build at 2025-09-26; 10:03:15
- Indigo Version 1.37.0-dev.4.0-g16ce0dfeb-wasm32-wasm-clang-19.0.0
- Chrome Version 140.0.7339.208 (Official Build) (64-bit)
- Win10

Found while testing - https://github.com/epam/ketcher/issues/7441

### PR DESCRIPTION
**Pull request by even1024**
## Generic request
- [ ] PR name follows the pattern `#1234 – issue name`
- [ ] branch name does not contain '#'
- [ ] base branch (master or release/xx) is correct
- [ ] PR is linked with the issue
- [ ] task status changed to "Code review"
- [ ] code follows product standards
- [ ] regression tests updated

### CODE REVIEW

File: core/indigo-core/molecule/src/query_molecule.cpp [hunk 1]
```diff
@@ -838,9 +838,20 @@ void QueryMolecule::writeSmartsAtom(Output& output, Atom* atom, int aam, int chi
         _getAtomChiralityDescription(atom, output);
         break;
     }
-    case ATOM_RSITE:
-        output.printf("*:%d", atom->value_min);
+    case ATOM_RSITE: {
+        int bits = atom->value_min;
+        int min_rgroup = 0;
+        for (int bit_idx = 0; bit_idx < 32; bit_idx++)
```
Comment (AlexanderSavelyev) [inline core/indigo-core/molecule/src/query_molecule.cpp]: add constant for 32. Very hard to understand the logic, please include comments for this section

**Review by AlexanderSavelyev — CHANGES_REQUESTED** [review]

File: core/indigo-core/molecule/src/query_molecule.cpp (hunk 1 above)
Comment (even1024) [reply core/indigo-core/molecule/src/query_molecule.cpp]: fixed

**Review by AlexanderSavelyev — APPROVED** [review]
